// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvlrilmqlnrpfspzugdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2bHJpbG1xbG5ycGZzcHp1Z2RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNTAzMjUsImV4cCI6MjA3MzcyNjMyNX0.9TJUC5RLFdbmHUzIl9PqymoXf7eozLvkELIp5wndLiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});